Homework
Leosmith23890/Selenium_Repo pull request #3
Opened 2021-12-23 08:13 UTC by Leosmith23890

Hi Ahsan,
Please review the Selenium Class 2 Homework

2022-01-11 00:44 UTC, ahsansiddiki requested changes

2022-01-11 00:44 UTC, ahsansiddiki commented on src/test/java/Class1/DarkSkyDate.java
> +        String dateInput="June-07-2021";
Not sure why you hard coding above line? I think its not necessary.

2022-01-11 00:44 UTC, ahsansiddiki commented on src/test/java/Class1/DarkSkyDate.java
> +
Just try below coding, works for me
        WebElement date1 = driver.findElement(By.xpath("(//time[@itemprop='datePublished'])[1]"));
        String text1 = date1.getText();
        System.out.println(text1);
        Date result = null;
        SimpleDateFormat dateChange=new SimpleDateFormat("MMMM d, yyyy");

        try {
            result = dateChange.parse(text1);
            boolean dateEquals=dateChange.format(result).equals(text1);
            Assert.assertTrue(dateEquals);
        }
        catch (ParseException e){
            e.printStackTrace();
        }

2022-01-11 00:44 UTC, ahsansiddiki commented on src/test/java/Class1/DarkSkyTemp.java
> +        System.out.println(".................................................");
You can have above/any System.out.println for your information/debugging but these are not necessary for automation. You can get rid of these before `git add`

2022-01-11 00:44 UTC, ahsansiddiki commented on src/test/java/Class1/DarkSkyTemp.java
> +            WebElement celsiusIndicator = MyDriver.getDriver().findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]/div/ul/li[4]"));
This xpath isn't good. it got too many dependencies.

2022-01-11 00:44 UTC, ahsansiddiki commented on src/test/java/Class1/Darksky.java
> +    System.out.println("The FeelsLike  "+feelsLikeField+" lies between "+lowField+" and  "+highField );
This is not correct way of verification. You need to do an assertion. Eg... 
boolean isTrue = currentTemp>lowTemp && currentTemp<highTemp;
Assert.assertTrue(isTrue);

2022-01-11 00:44 UTC, ahsansiddiki commented on src/test/java/Class1/FacebookSignUp.java
> +        WebElement textErrWeb=MyDriver.getDriver().findElement(By.xpath("//*[@class='_5633 _5634 _53ij']"));
This class value is random, I don't think its reliable. May be using text() is a better idea.

2022-01-11 00:44 UTC, ahsansiddiki commented on src/test/java/Class1/HotelCount.java
> +
Above work doesn't make good sense but you can follow below code for getting adult count.

        WebElement againElement = UseDriverClass.driver.findElement(By.xpath("//xpath')]"));
        String countString = againElement.getText();
        String[] roomAndGuest = countString.split(",");
        int roomCount = Integer.valueOf(roomAndGuest[0].substring(0,1));
        int guestCount = Integer.valueOf(roomAndGuest[1].trim().substring(0,1));
        //System.out.println(roomCount);
        //System.out.println(guestCount);
        Assert.assertTrue(roomCount==2,"The room count is not correct");
        Assert.assertTrue(guestCount==4,"The guest count is not correct");

2022-01-12 23:24 UTC, Leosmith23890 commented on src/test/java/Class1/HotelCount.java
> +
I have incorporated the codes Ahsan

2022-01-12 23:24 UTC, Leosmith23890 commented on src/test/java/Class1/FacebookSignUp.java
> +        WebElement textErrWeb=MyDriver.getDriver().findElement(By.xpath("//*[@class='_5633 _5634 _53ij']"));
I have incorporated the changes Ahsan

2022-01-12 23:24 UTC, Leosmith23890 commented on src/test/java/Class1/Darksky.java
> +    System.out.println("The FeelsLike  "+feelsLikeField+" lies between "+lowField+" and  "+highField );
I have incorporated the changes Ahsan

2022-01-12 23:24 UTC, Leosmith23890 commented on src/test/java/Class1/DarkSkyTemp.java
> +            WebElement celsiusIndicator = MyDriver.getDriver().findElement(By.xpath("/html/body/div[1]/div/div[1]/div[3]/div/ul/li[4]"));
I have changed the xpath Ahsan

2022-01-12 23:24 UTC, Leosmith23890 commented on src/test/java/Class1/DarkSkyTemp.java
> +        System.out.println(".................................................");
Sorry Ahsan,

Shall i keep it it will be useful for me when i revisit the code after sometime..plz plz

2022-01-12 23:24 UTC, Leosmith23890 commented on src/test/java/Class1/DarkSkyDate.java
> +
I have incorporated the codes Ahsan

2022-01-17 14:58 UTC, ahsansiddiki commented on src/test/java/Class1/DarkSkyTemp.java
> +        System.out.println(".................................................");
No worries! But now you know.

2022-01-17 14:59 UTC, ahsansiddiki approved these changes

2022-01-17 15:00 UTC, merged